### ISSUE TITLE
Error in README instruction

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/gitops-operator#12]
There is an error in the instructions in the README.

On applying the gitops catalog source given in the [README instructions ](https://github.com/redhat-developer/gitops-operator#making-the-operator-available-on-the-in-cluster-operatorhub) we encounter `Invalid value` error.

The name `Gitops-service-source` should not have uppercase character `G`

```
➜ cat gitops.yaml                  
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: Gitops-service-source
  namespace: openshift-marketplace
spec:
  displayName: 'Gitops Service by Red Hat'
  image: 'quay.io/redhat-developer/gitops-backend-operator-index:v0.0.1'
  publisher: 'Red Hat Developer'
  sourceType: grpc

➜ k apply -f gitops.yaml
The CatalogSource "Gitops-service-source" is invalid: metadata.name: Invalid value: "Gitops-service-source": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
