### ISSUE TITLE
Allow default ArgoCD instance to manage ResourceQuota, LimitRanges and CRDs.

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#192]
**Is your feature request related to a problem? Please describe.**
I would like to to create ResourceQuota and LimitRange objects for the namespaces I create with default Argo CD instance also I would like to manage customresourcedefinitions to install Sealed Secrets or Kubernetes External Secrets. 

So can we add the below permissions to the existing one's of default Argo CD instance.
ResourceQuotas
LimitRanges
CRDs

**Describe alternatives you've considered**
NA

**Additional context**
Currently users are creating a new role and rolebinding to provide the above permissions.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: openshift-gitops-argocd-extended-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
      - resourcequotas
      - limitranges
      # - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
    - argoproj.io
    resources:
      - argocds
    verbs:
      - '*'
  - apiGroups:
    - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - '*'
  - apiGroups:
    - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
```

**Comment by iam-veeramalla** [comment]
cc: @amitkrout

**Comment by pittar** [comment]
Thanks @iam-veeramalla for creating this issue.

A few notes:

Once https://issues.redhat.com/browse/GITOPS-1247 is resolved, I should be able to delete the `argocds` item:

```
  - apiGroups:
    - argoproj.io
    resources:
      - argocds
    verbs:
      - '*'
```

As for the entry for `sealedsecrets`, that probably shouldn't be included by default, as not everyone will be using Sealed Secrets.

Finally, the last entry (`customresourcedefinitions`) seems to be required to install both the Sealed Secrets operator and Kubernetes External Secrets.  Maybe this one is reasonable to include by default?
