### ISSUE TITLE
 SEC_ERROR_BAD_DER on argo instannce

### ISSUE THREAD

**Issue by chmouel** [redhat-developer/gitops-operator#277]
**Describe the bug**

I have installed Openshift Gitops Operator following the procedure from : 

https://docs.openshift.com/container-platform/4.9/cicd/gitops/installing-openshift-gitops.html

when trying to get to the argos instance I am getting this firefox ssl error : 

```
An error occurred during a connection to openshift-gitops-server-openshift-gitops.apps.paac.devcluster.openshift.com. security library: improperly formatted DER-encoded message.

Error code: SEC_ERROR_BAD_DER
```

my openshift router has a letsencrypt certificate on it and properly encrypted : 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/98980/153832021-06889960-159a-436d-a0b3-6f759338128a.png">

tried with firefox97 and with safari 15.3

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/98980/153832243-6356550a-67cc-49d3-996b-3c13dea26efa.png">

**Additional context**

**Comment by vrutkovs** [comment]
Same error here due to some odd self-signed cert. Chrome lets me bypass the error

**Comment by valumar** [comment]
The same for OpenShift version 4.8.26 and Red Hat OpenShift GitOps 1.4.1

**Comment by vrutkovs** [comment]
Workaround:
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
spec:
  server:
    route:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
```
