### ISSUE TITLE
unable to define envFrom secret for argocd-repo-server ArgoCD CRD

### ISSUE THREAD

**Issue by thpham** [redhat-developer/gitops-operator#281]
**Describe the bug**

Given the ArgoCD CRD [here](https://github.com/redhat-developer/gitops-operator/blob/master/config/crd/bases/argoproj.io_argocds.yaml#L887), we can define named env for the main repo server.
Unfortunately, when we want to extend argocd with plugin like it is documented for [argocd-vault-plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer), it is not possible.

**To Reproduce**
given this partial ArgoCD CR: see the `### HERE, NOT POSSIBLE`

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: foundations
  namespace: openshift-gitops
spec:
  ...
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME $${helm_args} . | argocd-vault-plugin generate -"]
  repo:
    ### HERE, NOT POSSIBLE
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials
    ###
    volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
    volumes:
    - name: custom-tools
      emptyDir: {}
    initContainers:
      - name: argocd-vault-plugin
        image: 'registry.redhat.io/ubi8/ubi:latest'
        command:
          - /bin/sh
          - '-c'
          - >-
            curl -v  -LJ --tls-max 1.2
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.9.0/argocd-vault-plugin_1.9.0_linux_amd64
            -o argocd-vault-plugin && chmod -v +x argocd-vault-plugin
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
        workingDir: /custom-tools
```

**Expected behavior**
Being able to inject env variables from secrets in the main argocd-repo-server container. 

**Screenshots**
none

**Additional context**
none

**Comment by thpham** [comment]
after some experimentation. it appears we can solve this with a different approach that if we were using argocd helm chart.

here is my finding:
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: foundations
  namespace: openshift-gitops
spec:
  ...
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate ./ --secret-name openshift-gitops:argocd-vault-plugin-credentials"]
    - name: argocd-vault-plugin-helm
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME $${helm_args} . | argocd-vault-plugin generate - --secret-name openshift-gitops:argocd-vault-plugin-credentials"]
  repo:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: VAULT_CACERT
        value: /vault/tls/ca.crt
    mountsatoken: true
    serviceaccount: argocd-vault-plugin
    volumeMounts:
      - name: custom-tools
        readOnly: true
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
      - name: vault-tls
        readOnly: true
        mountPath: /vault/tls/ca.crt
        subPath: ca.crt
    volumes:
    - name: custom-tools
      emptyDir: {}
    - name: vault-tls
      secret:
        secretName: vault-tls
    initContainers:
      - name: argocd-vault-plugin
        image: 'registry.redhat.io/ubi8/ubi-minimal:8.5-230'
        command:
          - /bin/sh
          - '-c'
          - >-
            curl -v  -LJ --tls-max 1.2
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.9.0/argocd-vault-plugin_1.9.0_linux_amd64
            -o argocd-vault-plugin && chmod -v +x argocd-vault-plugin
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
        workingDir: /custom-tools
```

beside this you have to create a `serviceAccount` with a role/rolebinding that is allowed to read secrets within the `openshift-gitops` namespace. And the `serviceAccount` has to be an authorised Vault role with kubernetes authentication type.

I hope it will spear some time to other people !
Cheers.

**Comment by domenecsos** [comment]
Hi, I was able to define env vars for the plugin by doing what is allowed in the CRD schema, which certainly does not include an `envProps` referencing a secret:
```
  repo:
    env:
      - name: VAULT_ADDR
        valueFrom:
          secretKeyRef:
            name: argocd-vault-plugin-credentials
            key: VAULT_ADDR
      - name: AVP_TYPE
        valueFrom:
          secretKeyRef:
            name: argocd-vault-plugin-credentials
            key: AVP_TYPE
      - name: AVP_AUTH_TYPE
        valueFrom:
          secretKeyRef:
            name: argocd-vault-plugin-credentials
            key: AVP_AUTH_TYPE
      - name: AVP_ROLE_ID
        valueFrom:
          secretKeyRef:
            name: argocd-vault-plugin-credentials
            key: AVP_ROLE_ID
      - name: AVP_SECRET_ID
        valueFrom:
          secretKeyRef:
            name: argocd-vault-plugin-credentials
            key: AVP_SECRET_ID
```
