### ISSUE TITLE
spec.ignoreDifferences.jqPathExpressions can't be used

### ISSUE THREAD

**Issue by dadav** [redhat-developer/gitops-operator#299]
**Describe the bug**
Can't use the `spec.ignoreDifferences.jqPathExpressions` option because the manifest validation fails.

This should be supported in version 2.2.8 (which is currently installed using this operator):
https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration

I think the cause of this is, that the CRD definition of the argocd-project and the one shipped with his operator are different.

Please compare these definitions:

https://github.com/argoproj/argo-cd/blob/release-2.2/manifests/crds/application-crd.yaml#L448

versus

https://github.com/redhat-developer/gitops-operator/blob/v1.4.0/config/crd/bases/argoproj.io_applications.yaml#L365

**To Reproduce**
1. Create an argocd application
2. Add this to the spec:

```yaml
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
```
3. Try to save it...

**Expected behavior**
`jqPathExpressions` can be used in the Application CRD.
