### ISSUE TITLE
Unable to adjust health check behavior of TLS certificates

### ISSUE THREAD

**Issue by okanarabaci** [redhat-developer/gitops-operator#411]
**Describe the bug**
I'm using custom TLS certificates for my applications in my OpenShift cluster that I create using a ClusterIssuer that creates LetsEncrypt certificates. They will look something like this:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-tls-cert
spec:
  secretName: external-tls-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
   dnsNames:
     - 'abc.def.com'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
```

When one is created, they will of course be managed in ArgoCD. The problem is that Argo doesn't recognize this as healthy and is trying to resync the certificate over and over. My solution was to attempt to create a custom health check that can mitigate this:

```
  resourceCustomizations: |
    cert-manager.io/Certificate: 
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
```

When I add this to the Argo CRD, I can see that it gets added to the `argocd-cm` but in the Argo UI it's still stuck in the OutOfSync loop.

Checking the status of the Certificate, I can see that it is healthy so there is nothing wrong with the certificate itself:

```
status:
  conditions:
    - lastTransitionTime: '2022-10-17T09:45:58Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 4
      reason: Ready
      status: 'True'
      type: Ready
```

**To Reproduce**
1. Create custom certificate
2. Manage it in GitOps
3. Check the UI to see that it's looping the sync because of OutOfSync status
4. Add custom health check for the certificate
5. Check `argocd-cm` to see that it gets picked up
6. Check the ArgoCD UI to see that nothing changes

**Expected behavior**
When I add a custom health check, I expect my certificates to be healthy and ready, and not get stuck in a sync loop.

**Additional context**
GitOps Operator v.1.5.7
OpenShift v.4.10

**Comment by okanarabaci** [comment]
Seems that the certificate must be defined fully with h/m/s and not only hours, otherwise this bug occurs. So changing my certificate to this solved it:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-tls-cert
spec:
  secretName: external-tls-cert
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
   dnsNames:
     - 'abc.def.com'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
```
