### ISSUE TITLE
--enable-helm - can't config the argocd-cm

### ISSUE THREAD

**Issue by tal-hason** [redhat-developer/gitops-operator#413]
**Describe the bug**
when want to configure the ArgoCD instance to render HELM chart with in a Kustomize folder, the option:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: --enable-helm
```

as mentioned in the argocd manual https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/

when updating the ConfigMap , the instance is always resting it to clean

even when adding the " kustomize.buildOptions: --enable-helm "

in the ArgoCD instance config, it still not create the option in the ConfigMap

**To Reproduce**
1. Go to 'the namespace where the ArgoCD instance is running
2. Click on 'ConfigMap, and search for argocd-cm'
3. Scroll down to 'then add in the data section the   kustomize.buildOptions: --enable-helm'
4. wait few seconds and reload the ConfigMap, and the configuration rest

**Expected behavior**
the  kustomize.buildOptions: --enable-helm should stay and enable the feature in ArgoCD
