### ISSUE TITLE
Can't set any Proxy for SCMProvider Generator in my ApplicationSet

### ISSUE THREAD

**Issue by hashbulla** [redhat-developer/gitops-operator#655]
**Describe the bug**

I am using the latest version of the operator, installed from Openshift Operator Hub (v1.11.1)
I have an ApplicationSet described as so:

```
- scmProvider:
       cloneProtocol: https
       gitlab:
          group: "<group number>"
          api: "<proxy access only self hosted gitlab api address>"
          tokenRef:
              secretName: <my secret name>
              key: password
          insecure: true
```

The GET request to the Gitlab group logged by the applicationset-controller works with curl from the applicationset-controller pod with the right proxy params, however returns a 403 FORBIDDEN probably meaning that it is a proxy setting error:

```
level=error msg="error generating params" error="error failed to get params for first generator in matrix generator: child generator returned an error on parameter generation: error listing repos: error listing projects for 25978: Get \"https://<my private gilab domain>/api/v4/groups/<my group id>/projects?include_subgroups=false&per_page=100&topic=&with_shared=true\": Forbidden"
```

However, I cannot ovewrite the applicationset-proxy manifest to add a `HTTP_PROXY` and `HTTPS_PROXY`. I cannot neither in the ApplicationSet scmprovider generator, nor template, nor repository section in the ArgoCD GUI nor in a kind: Secret file, connect to my Gitlab group nor set a proxy parameter that will be taken in consideration by the applicationset-controller.  

**To Reproduce**

Try to deploy an ApplicationSet with a scmprovider generator pointing to a proxy access only private self hosted gitlab group.

**Expected behavior**
The query found in applicationset-controller logs after applying my AppplicationSet manifest (`Get \"https://<my private gilab domain>/api/v4/groups/<my group id>/projects?include_subgroups=false&per_page=100&topic=&with_shared=true`) should use a proxy and connect to the Gitlab  group stated in the manifest.
