### ISSUE TITLE
Ignore differences when using the catalog source image template annotation

### ISSUE THREAD

**Issue by Jamstah** [redhat-developer/gitops-operator#676]
**Is your feature request related to a problem? Please describe.**
When ArgoCD is used to sync a catalog source that uses the `olm.catalogImageTemplate` to set the image name, the image is replaced using the template. ArgoCD then thinks the resource is out of sync, because the image name doesn't match the desired state.

See this repo as an example to sync: https://github.com/Jamstah/ibm-operator-catalog

**Describe the solution you'd like**
Automatically ignore that difference by ignoring fields set by the catalog manager, the same way we set tekton exclusions [here](https://github.com/redhat-developer/gitops-operator/blob/9093ffb73d98da0aaeaca02b3b618365ef74105e/controllers/argocd/argocd.go#L184).

In the default ArgoCD object, that would be:
```yaml
spec:
  resourceIgnoreDifferences:
    resourceIdentifiers:
      - customization:
          managedFieldsManagers:
            - catalog
        group: operators.coreos.com
        kind: CatalogSource
```

**Describe alternatives you've considered**
Without this, users need to ignore the difference themselves.
