### ISSUE TITLE
Update to ArgoCD 2.11.x

### ISSUE THREAD

**Issue by whitfiea** [redhat-developer/gitops-operator#730]
Is it possible to update this gitops-operator to pick up ArgoCD 2.11.x as it has a fix we require: https://github.com/argoproj/argo-cd/commit/e5c88c914b73e455f3f36dc24583e65c743da792

Is there a general process around when new versions in https://github.com/argoproj/argo-cd/releases will be picked up by this gitops-operator? or maybe a mechanism to allow users to state the ArgoCD version (within some boundary limits)?

**Comment by svghadi** [comment]
**gitops-operator v1.13** will pick up **ArgoCD 2.11.x**. We bump up minor version of Argo CD in each minor gitops-operator version release. For example
```
gitops-operator 1.10.x -> Argo CD 2.8.x  
gitops-operator 1.11.x -> Argo CD 2.9.x
gitops-operator 1.12.x -> Argo CD 2.10.x
gitops-operator 1.13.x -> Argo CD 2.11.x (not released)
gitops-operator 1.14.x -> Argo CD 2.12.x (not released)
```

If you want to try out some upstream feature which is not yet available in gitops-operator, you can set `.spec.image` & `.spec.version` in gitops-operator's ArgoCD CR to point to the upstream Argo CD image. 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: <your-argocd-instance>
spec:
  image: quay.io/argoproj/argocd
  version: v2.11.3
```
Note that the image upstream image is not built in Red Hat environment.

**Comment by svghadi** [comment]
**gitops-operator v1.13** will pick up **ArgoCD 2.11.x**. We bump up minor version of Argo CD in each minor gitops-operator version release. For example
```
gitops-operator 1.10.x -> Argo CD 2.8.x  
gitops-operator 1.11.x -> Argo CD 2.9.x
gitops-operator 1.12.x -> Argo CD 2.10.x
gitops-operator 1.13.x -> Argo CD 2.11.x (not released)
gitops-operator 1.14.x -> Argo CD 2.12.x (not released)
```

If you want to try out some upstream feature which is not yet available in gitops-operator, you can set `.spec.image` & `.spec.version` in gitops-operator's ArgoCD CR to point to the upstream Argo CD image. 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: <your-argocd-instance>
spec:
  image: quay.io/argoproj/argocd
  version: v2.11.3
```
Note that the image upstream image is not built in Red Hat environment.
