### ISSUE TITLE
SSO does not work when global proxy is configured for OCP

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-developer/gitops-operator#91]
**Is your feature request related to a problem? Please describe.**
Having to extract a admin token from secrets isn't very user-friendly.
It would be better if the argo instance was setup with SSO using the existing oauth server in ocp.

**Describe the solution you'd like**
SSO using OCP oauth.

**Describe alternatives you've considered**
none in particular

**Additional context**
N/A

**Comment by davidkarlsen** [comment]
After digging around I see that there seems to be integration in place, however the operator just says "{"level":"info","ts":1616417678.2982924,"logger":"controller_argocd","msg":"reconciling for dex, but dex is disabled"}
"

our CR:
```
k get argocd test -o yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: "2021-03-22T12:22:14Z"
  generation: 11
  name: test
  namespace: pti-stest
  resourceVersion: "433157028"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/pti-stest/argocds/test
  uid: e41f37e9-2c1f-4291-89eb-74671f44d369
spec:
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  dex:
    openShiftOAuth: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  redis:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  repo-server:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  server:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    route:
      enabled: true
  statusBadgeEnabled: true
```

**Comment by iam-veeramalla** [comment]
Hi @davidkarlsen , Thanks for reaching out. 

Dex is disabled by default. It can be enabled by following below steps.

```
spec:
  config:
    env:
    - name: DISABLE_DEX
      Value: "false"
```

You can enable RBAC on argo-cd by following the instructions provided in the argo-cd RBAC Configuration. Example RBAC configuration looks like this.
```
spec:
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'

```


Detailed steps are available here:
https://docs.google.com/document/d/1147S5yOdj5Golj3IrTBeeci2E1CjAkieGCcl0w90BS8/edit?ts=602bd66f#

**Comment by davidkarlsen** [comment]
> Hi @davidkarlsen , Thanks for reaching out.
> 
> Dex is disabled by default. It can be enabled by following below steps.
> 
> ```
> spec:
>   config:
>     env:
>     - name: DISABLE_DEX
>       Value: "false"
> ```
> 
> You can enable RBAC on argo-cd by following the instructions provided in the argo-cd RBAC Configuration. Example RBAC configuration looks like this.
> 
> ```
> spec:
>   dex:
>     openShiftOAuth: true
>   rbac:
>     defaultPolicy: 'role:readonly'
>     policy: |
>       g, system:cluster-admins, role:admin
>     scopes: '[groups]'
> ```
> 
> Detailed steps are available here:
> [docs.google.com/document/d/1147S5yOdj5Golj3IrTBeeci2E1CjAkieGCcl0w90BS8/edit?ts=602bd66f#](https://docs.google.com/document/d/1147S5yOdj5Golj3IrTBeeci2E1CjAkieGCcl0w90BS8/edit?ts=602bd66f#)

nice, those docs are not linked from the repo?
And it is closed. I asked for access now.

**Comment by pburgisser** [comment]
My question is more, are we going to be able to set the ArgoCD parameters such as DEX SSO when instanciating the GitOps so I eliminate a step to post-configure ArgoCD to enable the SSO

@iam-veeramalla I don't have access to your Google Document

**Comment by davidkarlsen** [comment]
> My question is more, are we going to be able to set the ArgoCD parameters such as DEX SSO when instanciating the GitOps so I eliminate a step to post-configure ArgoCD to enable the SSO

+1
It is not a smooth UX as of now. Lack of documentation and bad defaults make it a bad experience. It should come with sane default out of the box.

**Comment by iam-veeramalla** [comment]
@davidkarlsen @pburgisser we are working on the documentation. It will be available post GA. We have plans to automate SSO without user having to configure any additional steps. Unfortunately that is also after GA.

For now, User have to perform below steps manually. 

```
Dex is disabled by default. It can be enabled by following below steps.

spec:
  config:
    env:
    - name: DISABLE_DEX
      Value: "false"

You can enable RBAC on argo-cd by following the instructions provided in the argo-cd RBAC Configuration. Example RBAC configuration looks like this.

spec:
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
```
