### ISSUE TITLE
ArgoCD image missing tar

### ISSUE THREAD

**Issue by cnocula-i** [redhat-developer/gitops-operator#99]
**Describe the bug**
Applications with Helm charts defined in a chart repository fail to be deployed.

**To Reproduce**
1. Create an application with a hosted Helm chart, e.g.:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  project: my-project
    repoURL: 'https://my-helmchart.repository.org/helm/'
    targetRevision: 0.1.0
    chart: my-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
2. Attempt to synchronize the application
3. See error
```
rpc error: code = Unknown desc = exec: "tar": executable file not found in $PATH
```

**Expected behavior**
Chart is downloaded as a "tgz" file and processed correctly.

**Screenshots**

**Additional context**
